spring:
  application:
    name: rest-client-app

  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
      hibernate:
        generate_statistics: true
    show-sql: true
server:
  port: 8084

